name: Package Action

on:
  push:
    branches:
      - staging
      - beta

permissions:
  contents: write

jobs:
  package-action:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20

      - name: Package Action
        run: |
          npm i
          npm run build
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "chore: Update dist" || echo "No changes to commit"
          git push
