name: Package Action

on:
  push:
    branches:
      - staging
      - beta

permissions:
  contents: write

jobs:
  package-action:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Use Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 20

      - name: Package Action
        run: |
          npm i
          npm run build
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "chore: Update dist" || echo "No changes to commit"
          git push
